spring:
  datasource:
    url: jdbc:postgresql://localhost:${DATABASE_PORT:5432}/${DATABASE_NAME:profile_service}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  level:
    root: info
    xyz:
      catuns:
        edupulse:
          profile: debug
server:
  port: 8084